spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dynamicapi
    username: postgres
    password: 25076600
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: "f3d9a7c8b1e2d4f6g8h9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6A7B8C9D0E1F2G3H4I5J6K7L8M9N0O1P2Q3R4S5T6U7V8W9X0Y1Z2a3b4c5d6e7f8g9h0i1j2k3l4m5n6o7p8q9r0s1t2u3v4w5x6y7z8A9B0C1D2E3F4G5H6I7J8K9L0M1N2O3P4Q5R6S7T8U9V0W1X2Y3Z4a5b6c7d8e9f0g1h2i3j4k5l6m7n8o9p0q1r2s3t4u5v6w7x8y9z0A1B2C3D4E5F6G7H8I9J0K1L2M3N4O5P6Q7R8S9T0U1V2W3X4Y5Z6a7" # Substitua por uma chave segura
  expiration: 86400000 # Tempo de expiração em milissegundos (ex.: 1 dia)

server:
  port: 8080

logging:
  level:
    org.springframework.security: DEBUG
    com.example.dynamicapi.security: DEBUG